Repository Blazored/Modal, pull requests merged in 2020-09, with the labels that each got.

#222 Add option for setting if content of Modal is scrollable, this helps …
  samples/BlazorWebAssembly/Pages/ScrollableContent.razor
  samples/BlazorWebAssembly/Shared/FullContentPage.razor
  samples/BlazorWebAssembly/Shared/NavMenu.razor
  src/Blazored.Modal/BlazoredModalInstance.razor
  src/Blazored.Modal/BlazoredModalInstance.razor.cs
  src/Blazored.Modal/Configuration/ModalOptions.cs
  src/Blazored.Modal/wwwroot/blazored-modal.css
  tests/src/Blazored.Modal.Tests/ModalOptionsTests.cs
Labels: Feature

#227 Gracefully close modal when close is called
  src/Blazored.Modal/BlazoredModal.razor.cs
  src/Blazored.Modal/BlazoredModalInstance.razor
  src/Blazored.Modal/Configuration/ModalReference.cs
  src/Blazored.Modal/Services/ModalService.cs
  tests/src/Blazored.Modal.Tests/DisplayTests.cs
Labels: Maintenance

#231 [Bugfix] Navigate Away
  samples/BlazorWebAssembly/Pages/NavigateAfterModal.razor
  samples/BlazorWebAssembly/Shared/NavMenu.razor
  src/Blazored.Modal/BlazoredModal.razor.cs
Labels: Bug

#233 [Bugfix] Fixes representation of animation duration when the current culture doesn't use a period as the decimal separator
  src/Blazored.Modal/BlazoredModalInstance.razor
  src/Blazored.Modal/BlazoredModalInstance.razor.cs
Labels: Bug

#226 Added allowOutsideClick to capture clicks outside the focus trap
  src/Blazored.Modal/Interop/Blazored.Modal.ts
Labels: Bug
