Repository Blazored/Modal, pull requests merged in 2024-02, with the labels that each got.

#554 Upgraded docusaurus to latest version and updated custom overlay doc
  docs/docs/styling/custom-overlay.md
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  samples/BlazorWebAssembly/wwwroot/css/app.css
Labels: Docs

#453 Added two new animation types
  samples/BlazorWebAssembly/Pages/Animation.razor
  src/Blazored.Modal/BlazoredModalInstance.razor.cs
  src/Blazored.Modal/BlazoredModalInstance.razor.css
  src/Blazored.Modal/Configuration/ModalAnimationType.cs
Labels: Feature

#530 Fix for scroll position going to Top when using multple modals
  src/Blazored.Modal/BlazoredModalInstance.razor.cs
Labels: Bug

#556 Swap to CSS grid for position middle
  src/Blazored.Modal/BlazoredModalInstance.razor.css
Labels: Bug

#560 Removed markup and logic used for previous debugging
  src/Blazored.Modal/FocusTrap.razor
Labels: Bug

#559 Use computed style to consider the real values
  src/Blazored.Modal/BlazoredModal.razor.js
Labels: Bug
